# Generated by Django 2.0.5 on 2018-05-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('dateId', models.AutoField(db_column='dateId', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('finishTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.UUIDField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('startVote', models.DateTimeField()),
                ('finishVote', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kandleapp.User'),
        ),
        migrations.AddField(
            model_name='date',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kandleapp.Event'),
        ),
        migrations.AddField(
            model_name='date',
            name='users',
            field=models.ManyToManyField(to='kandleapp.User'),
        ),
    ]
