# Generated by Django 2.0.5 on 2018-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandleapp', '0002_auto_20180526_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventId',
        ),
        migrations.AddField(
            model_name='event',
            name='eventUrl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
