# Generated by Django 2.0.5 on 2018-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandleapp', '0004_auto_20180529_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closedForVote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='startTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='finishVote',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startVote',
            field=models.DateField(),
        ),
    ]
